### ISSUE TITLE
Expose additional MQTT settings as optional parameters 

### ISSUE THREAD

**Issue by mjbranson** [IBMStreams/streamsx.iot#61] opened 2017-06-30 19:56 UTC
Allow the user of the composite operators in the toolkit toolkit to set the underlying MQTTSource/Sink values for the retry policy, keepalive, timeout, and client ID.

We had a problem reported by a Bluemix Streaming Analytics customer about data flow stopping which looks like its due the MQTTSource default of the retry parameter to 5.   

Also, it looks like there's the possibility of name collisions on the generated client IDs in the toolkit, if the user has two Streams instances and the same Streams app is submitted to both (and runs under the same job number).

**Comment by ddebrunner** [comment] 2017-06-30 23:34
I entered an issue against the MQTT operators, as I think the root cause of the data stopping is the behaviour of those operators once the reconnect limit is reached.

https://github.com/IBMStreams/streamsx.messaging/issues/312

**Comment by ddebrunner** [comment] 2017-07-01 17:10
>  Streaming Analytics customer about data flow stopping which looks like its due the MQTTSource default 

Be good to verify it was the MQTTSource not being connected and not failing. Looking at the code it seems if the operator could not connect after 5 retries it should have failed, restarted etc.

**Comment by schulz2** [comment] 2017-07-07 08:22
Has it been confirmed that it is the 'idling' MQTT operator that caused the problems?

**Comment by rnostream** [comment] 2021-03-23 11:33
Close this as streamsx.mqtt should be used now directly.

**Closed by rnostream** 2021-03-23 11:33 UTC
Labels: wontfix
